# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Set keyboard backlight to medium on startup
exec-once = asusctl leds set med

# Auto-mount USB drives with tray icon
exec-once = udiskie --smart-tray
